[project]
name = "ECPostcodeLookupPages"
version = "0.0.0"
description = "tbd"
readme = "README.md"
requires-python = "==3.12.*"

[tool.ruff]
line-length = 80
lint.ignore = ["E501"]
lint.extend-select = [
    "I",
    "C4",
    "SIM",
    "Q003",
    "RET",
]

[tool.coverage.report]
exclude_lines = [
    "if __name__ == .__main__.:",
    "@abstractmethod"
]

[tool.pytest.ini_options]
pythonpath = ["postcode_lookup"]
