build-ECPostcodeLookupFunction:
	pip install --break-system-packages setuptools
	pip install --upgrade -r requirements.txt --target "$(ARTIFACTS_DIR)/python/"

build-BasicAuthFunction:
	pip install --break-system-packages setuptools
	pip install --upgrade -r requirements.txt --target "$(ARTIFACTS_DIR)/python/"
