build-ECPostcodeLookupFunction:
	cp --recursive . "$(ARTIFACTS_DIR)/"
	pip install --break-system-packages setuptools
	pip install --upgrade -r requirements.txt --target "$(ARTIFACTS_DIR)/"

build-BasicAuthFunction:
	cp --recursive . "$(ARTIFACTS_DIR)/"
	pip install --break-system-packages setuptools
	pip install --upgrade -r requirements.txt --target "$(ARTIFACTS_DIR)/"
